<?php
$this->placeholder('mainTitle')->set($this->ShowMessages($this->flashMessenger));
?>
<style>
    input[type=text]{
		-webkit-appearance: none; -moz-appearance: none;
		display: block;
		margin: 0;
		width: 100%; height: 40px;
		line-height: 40px; font-size: 17px;
		border: 1px solid #bbb;
		padding-bottom:10px;		
		}
     select {
            font-size: 110%;
            padding: 0 0 0 0px;
            height: 35px;
    }
    input[type=number]{
		-webkit-appearance: none; -moz-appearance: none;
		display: block;
		margin: 0;
		width: 60px; height: 40px;
		line-height: 40px; font-size: 17px;
		border: 1px solid #bbb;
		padding-bottom:10px;		
		}
                input.schifting{
		-webkit-appearance: none; -moz-appearance: none;
		//display: block;
		//margin: 0;
		width: 60px; height: 40px;
		line-height: 40px; font-size: 17px;
		border: 1px solid #bbb;
		padding-bottom:10px;	
                margin-left:50%;
		}
                
                table  {
                    font-size:20px;
                }
                .finale td {
                    line-height: 24px;
                    padding-bottom: 1em;
                }
               input[type=submit] {
    background-color: #004f9f;
    border: none;
    color: white;
    padding: 16px 32px;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;
    font-size:24px;
}
.standing {
    color: #004f9f;
}
</style>
<form name="wkprono" id="wkprono" method="post" action="/index/prono">
<table width="820" cellspacing="5" cellpadding="5" border="0">
	<tbody>
		<tr>
		<td valign="top">
			<label><?php echo $this->translate("Naam");?>:</label> <input type="text" name="naam"  size="60">
		</td>
                </tr>                
                <tr>
		<td valign="top">
			<label>E-mail:</label> <input type="text" name="email"  size="60">
		</td>
		</tr>
        <tr>
		<td valign="top">
			<label><?php echo $this->translate("Team");?>:</label> <input type="text" id="team" name="team"  size="60">
		</td>
        </tr>
        <tr>
        <td valign="top">
		<div class="infoteambox">
        Als extra kan je naast het individuele klassement ook deelnemen aan een teamklassement. Geef hiervoor met minstens 3 personen dezelfde teamnaam op. <br/>Er is een extra prijs voor het beste team !
        </div>
		</td>
		</tr>

		<tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,1); ?>
		</td>
                </tr>                
                <tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,2); ?>
		</td>
                </tr>
                <tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,3); ?>
		</td>
                </tr>
                <tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,4); ?>
		</td>
                </tr>
		<tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,5); ?>
		</td>
                </tr>
                <tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,6); ?>
		</td>
                </tr>
		<tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,7); ?>
		</td>
                </tr>
                <tr>
		<td valign="top">
			<?php echo $this->GetGroepsWedstrijden($this->wedstrijden,8); ?>
		</td>
                </tr>
                
		<tr>
		<td width="50%" valign="top" colspan="2">
                    <a href="#" class="standing">Stand Groep</a>
                </td>		
		</tr>
                
                <tr>
		<td width="50%" valign="top" colspan="2">
                    <div id="divLoading2"></div>
                </td>		
		</tr>
		
		<tr>
		<td valign="top">
			<?php echo $this->GetFinaleWedstrijden(8,$this->ploegen,$this->wedstrijden[9]); ?>
		</td>
		</tr>		
		<tr>
		<td valign="top">
			<?php echo $this->GetFinaleWedstrijden(4,null,$this->wedstrijden[10]); ?>
		</td>
		</tr>		
		<tr>
		<td valign="top">
			<?php echo $this->GetFinaleWedstrijden(2,null,$this->wedstrijden[11]); ?>
		</td>
		</tr>       
                <tr>
		<td valign="top">
			<?php echo $this->GetFinaleWedstrijden(1,null,$this->wedstrijden[12]); ?>
		</td>
		</tr> 

        <tr>
		<td valign="top">
			<?php echo $this->GetFinaleWedstrijd(1,$this->wedstrijden[13]); ?>
		</td>
		</tr>
			               			
		<tr>
		<td colspan="2" valign="top" style="text-align:center;">
			<?php echo $this->GetSchiftingsvraag(1); ?>
		</td>
		</tr>
                
                <tr>
                <td colspan="2" valign="top" style="text-align:center;">
                <input type="submit" value="<?php echo $this->translate('Sla deze pronostiek op !'); ?>" name="btn_save" id="btn_save">
                </td>                
                </tr>
		
	</tbody>
</table>
</form>
<br/>
<br/>
<div id="divLoading"></div>
<div id="messages"></div>
<?php echo $this->render('/index/_jsCustom_prono.phtml'); ?>